export const COLLECTIONS = [
  { id: "home__achievementsstatsdata", label: "Home: Stats" },
  // { id: "home__admissionsdata", label: "Home: Admissions" },
  // { id: "home__allhomedata", label: "Home: All Data" },
  // { id: "home__announcementsdata", label: "Home: Announcements" },
  { id: "home__carouseldata", label: "Home: Carousel" },
  // { id: "circular__circularpreviewdata", label: "Circulars: Circulars" },
  { id: "home__missionvisiondata", label: "Home: Mission/Vision" },
  { id: "home__newstickerdata", label: "Home: News Ticker" },
  { id: "home__ourcampusdata", label: "Home: Our Campus" },
  { id: "home__ourleads", label: "Home: Our Leads" },
  { id: "home__ourschoolscollegesdata", label: "Home: Schools/Colleges" },
  { id: "home__recruitersdata", label: "Home: Recruiters" },
  { id: "home__testimonialdata", label: "Home: Testimonials" },
  // { id: "home__welcomedata", label: "Home: Welcome" },
  { id: "documents", label: "Documents" },
  { id: "aasc-beats__aascbeatsdata", label: "AASC Beats" },
  { id: "about__chiefmentordata", label: "About: Chief Mentor" },
  { id: "about__principaldata", label: "About: Principal" },
  { id: "about__profileofcollegedata", label: "About: College Profile" },
  // { id: "about__governingbodycouncildata", label: "About: Governing Body" },
  { id: "about__ourteamdata", label: "About: Our Team" },
  { id: "about__pressreleasesdata", label: "About: Press Releases" },
  { id: "contact__contactdata", label: "Contact Data" },
  { id: "academics__academiccalendardata", label: "Academics: Calendar" },
  { id: "academics__departmentsdata", label: "Academics: Departments" },
  { id: "academics__pgprogrammsdetails", label: "Academics: PG Programs" },
  { id: "academics__prospectusdata", label: "Academics: Prospectus" },
  { id: "academics__ugprogramsdatadetails", label: "Academics: UG Programs" },
  { id: "academics__valueaddedcoursesdata", label: "Academics: Value Added" },
  { id: "campus-life__seeddata", label: "Campus Life" },
  { id: "commitees__committiesdata", label: "Committees" },
  // { id: "events__eventsdata", label: "Events" },
  // {
  //   id: "events__upcommingeventspreviewdata",
  //   label: "Events: Upcoming Preview",
  // },

  // { id: "iqac__nirfdata", label: "IQAC: NIRF" },
  { id: "placements__placementrecords", label: "Placements: Records" },
  {
    id: "placements__trainingandplacementsdata",
    label: "Placements: Training",
  },
];
