name: Frontend CI

on:
  push:
    branches: [main]
    paths: 
      - 'client/**'
      - '.github/workflows/deploy.yml'
  pull_request: 
    branches: [main]
    paths: 
      - 'client/**'
      - '.github/workflows/deploy.yml'



jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - name: Install dependencies
        working-directory: ./client
        run: npm install --legacy-peer-deps
      - name: Run Vitest Tests
        working-directory: ./client
        run: npm test -- --run # '--run' makes sure it doesn't stay in "watch" mode
      - name: Build Project
        working-directory: ./client
        run: npm run build

      - name: 🚀 Deploy to Namecheap
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./
          port: 21
          timeout: 90000